- name: Demo on using shell 
  hosts: all         
  tasks: 
    - name: Demo on using shell
      ansible.builtin.shell: uptime 
      register: OUT

    - name: Printing the shell output
      ansible.builtin.debug:  
        msg: "{{ OUT }}"