- name: Demo on ansible vault
  hosts: all
  hosts:
    USERNAME: sqlroot
    PASSWORD: robo@1
  tasks: 
    - name: Printing the output
      ansible.builtin.debug:
        msg: "Printing the password {{ PASSWORD }}"