- name: Disable existing {{ packageName }} module stream for {{ component }} server
  ansible.builtin.shell: dnf module disable {{ packageName }} -y

- name: Enable {{ packageName }} module stream {{ packageVersion }}
  ansible.builtin.shell: dnf module enable {{ packageName }}:{{ packageVersion }} -y

- name: Installing "{{ packageName }}" 
  ansible.builtin.package:
    name: "{{ packageName }}" 
    state: present

- name: Configuring the hostName
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }}