- name: Set Prompt
  ansible.builtin.shell: set-hostname github-runner-node

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable and start Docker service
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  ansible.builtin.command: docker info
  register: docker_info
  changed_when: false

- name: Add ec2-user to docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: yes


