- name: Configuring the {{ component }} repo 
  ansible.builtin.copy:
    src: "{{ component }}.repo"
    dest: /etc/yum.repos.d/{{ component }}.repo

- name: Installing "{{ packageName }}" 
  ansible.builtin.package:
    name: "{{ packageName }}" 
    state: present

- name: Enabling the visibility of "{{ packageName }}" service
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting "{{ packageName }}" service
  ansible.builtin.service:
    name: mongod
    enabled: yes
    state: restarted

# Clones the repo 
- name: Clone on the remote host - {{ component }} service
  ansible.builtin.git:
    repo: 'https://github.com/B60-CloudDevOps/catalogue.git'
    dest: /tmp/checkout
    version: main

- name: Injecting MongoDB Master Data
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.robotshop.fun </tmp/checkout/db/master-data.js 

- name: Configuring the hostName
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }}