- name: Disable existing {{ packageName }} module stream for {{ component }} server
  ansible.builtin.shell: dnf module disable {{ packageName }} -y

- name: Enable {{ packageName }} module stream {{ packageVersion }}
  ansible.builtin.shell: dnf module enable {{ packageName }}:{{ packageVersion }} -y

- name: Installing "{{ packageName }}" 
  ansible.builtin.package:
    name: "{{ packageName }}" 
    state: present

- name: Creating user and configuring the app directory for {{ component }} service
  ansible.builtin.include_role:
    name: common                 
    tasks_from: createUserAndApp           # name of the task file    

- name: Generating artifact dependencies for {{ component }} service
  community.general.npm:
    path: "{{ appDirectory }}" 

- name: Injecting the mongodb schema for {{ component }} service
  ansible.builtin.include_role:
    name: common                 
    tasks_from: injectMongoSchema           # name of the task file    

- name: Configuring service
  ansible.builtin.include_role:
    name: common                 
    tasks_from: configureService           # name of the task file    

- name: Configuring the hostName
  ansible.builtin.include_role:
    name: common                 
    tasks_from: setHostname      